version: "3.8"

services:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512m
    ports:
      - 8080:8080
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - backend
    depends_on:
      - mysql
    ports:
      - "9000:9000" # Port PHP-FPM

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8001:80" # Port untuk mengakses aplikasi Laravel
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend

  mysql:
    image: mysql:8.0.32
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g
    ports:
      - 3306:3306
    networks:
      - backend

networks:
  backend:
    driver: bridge
