server {
    listen 80;
    server_name dashweb.site;

    root /var/www/public;  # Arahkan ke folder 'public' Laravel

    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # Gantilah include dengan path yang benar jika Anda menambahkan fastcgi-php.conf
        include fastcgi_params;  # Menggunakan file fastcgi_params standar
        fastcgi_pass php-fpm:9000;  # Mengarahkan ke container PHP-FPM (php-fpm:9000)
        fastcgi_param SCRIPT_FILENAME /var/www$document_root$fastcgi_script_name;  # Path script PHP yang benar
        fastcgi_param DOCUMENT_ROOT /var/www/public;  # Pastikan document root mengarah ke public Laravel
    }

    location ~ /\.ht {
        deny all;
    }
}
