server {
    listen 80;
    server_name dashweb.site;

    root /var/www/public;  # Arahkan ke folder 'public' Laravel

    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php-fpm-container:9000;  # Nama layanan harus sesuai dengan docker-compose.yml
        fastcgi_param SCRIPT_FILENAME /var/www$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}
